# Generated by Django 4.1.7 on 2023-04-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "task_manager",
            "0003_project_projecttype_team_task_project_project_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
