# Generated by Django 4.1.7 on 2023-04-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0007_alter_post_task_alter_task_assignees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="task_manager.task",
            ),
        ),
    ]
