# Generated by Django 4.1.7 on 2023-04-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0011_alter_commentary_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="fact_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
