# Generated by Django 4.1.7 on 2023-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0012_project_fact_date_task_fact_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, upload_to="foto_users/"),
        ),
    ]
