# Generated by Django 4.1.7 on 2023-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0014_alter_post_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, upload_to="static/foto_users/"),
        ),
    ]
