# Generated by Django 4.1.7 on 2023-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0015_alter_employee_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, upload_to="media/foto_users/"),
        ),
    ]
