# Generated by Django 4.1.7 on 2023-04-17 18:17

from django.db import migrations


def forwards_func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'fixture_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0016_alter_employee_photo"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
